

baseURL = 'https://plomeroquito24h.com/'
languageCode = 'es-es'
title = 'Plomero Quito - Servicios 24/7'

[params]
telefono = "0981682407"
whatsapp = "593981682407"
direccion = "Quito, Ecuador"
horario = "Atención 24/7"
empresa = "Plomero Quito"
